version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      - GEMINI_API_KEY_1=${GEMINI_API_KEY_1}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/api/ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
